apiVersion: apps/{{ .Values.apiVersion }}
kind: Deployment
metadata:
  name: quotes-api
  labels:
    app: {{ template "demo42.name" . }}
    chart: {{ template "demo42.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}  
spec: 
  replicas: {{ .Values.api.replicas }}
  selector:
    matchLabels:
      app: quotes-api
  template: 
    metadata:
     labels:
        app: quotes-api
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: quotes-api
        image: {{ .Values.api.image }}
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: ConfigPath
          value: "/etc/secrets"
        volumeMounts:
            - name: app-secrets
              mountPath: "/etc/secrets"
      volumes:
      - name: app-secrets
        secret:
          secretName: quotes-secret
          defaultMode: 256
      imagePullSecrets:
        - name: app-registry-secret
---
apiVersion: v1
kind: Service
metadata:
    # used for in-cluster dns discovery
    name: quotes-api
spec:
    ports:
        - port: 80
          protocol: TCP
          targetPort: 80
    selector:
        app: quotes-api
    type: ClusterIP
    
